apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: Amor573/landing-page:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-regcred
